index:
  path: /
  controller: App\Controller\HomeController::indexAction
productView:
  path: /product/view/{id}
  controller: App\Controller\ProductController::viewAction
categoryView:
  path: /category/view/{id}
  controller: App\Controller\CategoryController::viewAction